### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by DRAEYE** [hitagisol/PX4FLOW_mavlink_read#1]
Excuse me ,I came across the problem of "'NoneType' object has no attribute 'read'" when run the program ,how can i deal with this problem please?

**Comment by hitagisol** [comment]
Hi! You counter this error when running the test.py? Could you please provide me more comprehensive error message when you running it? Such as which class/function is this error occurs?

**Comment by hitagisol** [comment]
Hi! You counter this error when running the test.py? Could you please
provide me more comprehensive error message when you running it? Such as
which class/function is this error occurs?

DRAEYE <notifications@github.com> 于2018年8月3日周五 下午2:27写道：

**Comment by DRAEYE** [comment]
I tried to run the code under Ubuntu just now ,and replace the path of tty as "/dev/ttyACM0" instead of "ttyACM0",and it works. THANKS! Maybe it's similar under windows!

**Comment by hitagisol** [comment]
Yes, in windows the port is named as "COMx", in my computer it is "COM4"
and this may vary on different PCs. Anyway, I'm glad that the code can make
some help for you! :)

DRAEYE <notifications@github.com> 于2018年8月4日周六 上午8:58写道：
